extends Node

var SHITPOST_DIALOGUES = [
	"le puse una bisagra a una hoja y ahora tengo apego a una tabla con olor a trementina",
	"yo no vivo, yo funciono como cerradura oxidada: a veces abro, a veces sangro",
	"metí una lija en una puerta y salió un recuerdo de 2009, bro",
	"¿esto es una gubia o una extensión de mis traumas?",
	"la madera me dijo que no estaba lista para ser trabajada y yo lloré con ella",
	"¿cómo que el marco no encaja? literal yo en todas mis relaciones",
	"intenté cuadrar la puerta, pero lo que está desalineado soy yo desde que nací",
	"cada tornillo es una mentira que me contaron en la infancia",
	"me preguntaron si era carpintero. les dije que soy un glitch estructural con herramientas",
	"cerré una puerta tan fuerte que desbloqueé un trauma interdimensional",
	"barnicé una hoja y se reflejó mi ansiedad en ella",
	"esta tabla tiene más nudos que mis relaciones con figuras paternas",
	"el cliente pidió una puerta minimalista. le di silencio y una crisis existencial",
	"mi serrucho empezó a hablarme. le respondí. estamos saliendo",
	"llevé una tabla al taller y terminé llevándome un espejo emocional",
	"clavé un clavo torcido y pensé: ‘same’",
	"si esta puerta no gira bien es porque refleja mi ciclo de validación externa",
	"nunca le puse manilla y aún así se abrió… trauma reconocido",
	"esta traba me habló en código morse emocional. respondí con ansiedad",
	"le cambié la bisagra pero igual se sigue cerrando cuando intento confiar",
	"barnicé con tanto odio que ahora brilla con rencor",
	"la puerta chirrió y entendí que también quiere llorar sin molestar",
	"la hoja se abrió y me dijo ‘vos tampoco sos estable, bro’",
	"intenté arreglarla pero me terminó arreglando a mí. plot twist",
	"no instalo puertas, instalo dilemas éticos con forma rectangular",
	"el picaporte me juzga. siento que sabe que me gusta sufrir",
	"¿lija de 100 o de 80? igual ninguna suaviza mi ansiedad",
	"puse una cerradura tan compleja que ni yo puedo salir de mi mente",
	"la puerta tenía nivel, pero le faltaba autoestima",
	"todo iba bien hasta que la puerta preguntó ‘¿y qué somos?’",
	"no pude terminar el marco porque me puse a cuestionar mi propósito vital",
	"golpearon la puerta y reaccioné como si fuera una crítica personal",
	"cada vez que alineo una hoja, una parte de mí se desajusta",
	"trabajo en silencio porque si hablo me descubren como personaje secundario",
	"la puerta era de pino. como mi identidad: suave, barata y hueca",
	"cerré tan fuerte que rebotó mi última relación",
	"me metí al taller a poner traba y salí con disociación activa",
	"creo que esta puerta me gusta. no sé si sexual o existencialmente",
	"le puse una aldaba y me dijo 'no soy esa clase de estructura, gato'",
	"me encerré en el galpón con 14 tablas y un miedo inexplicable a ser amado",
	"esto ya no es un trabajo. es una intervención de emergencia emocional con clavos",
	"puerta instalada pero me olvidé de instalarme autoestima",
	"esta puerta se trabó y ahora es canon en el universo del dolor",
	"no es lija, es depilación energética de trauma estructural",
	"le puse una bisagra y ahora cree en el horóscopo",
	"mi taladro vibró más que yo en cualquier interacción humana",
	"soy soporte técnico emocional para puertas con abandono",
	"la puerta me dijo que no soy compatible con su firmware",
	"barnicé una hoja y me empezó a gaslightear",
	"esto no es un taller, es un glitch emocional con herramientas",
	"le hice una puerta a alguien y ahora sueña con cerrarme",
	"le puse cerradura y ahora se siente con derecho a elegir sus vínculos",
	"no soy un gato, soy un bug con textura peluda",
	"tengo una sierra que corta madera pero no vínculos tóxicos",
	"la puerta me habló en binario y entendí que necesitaba contención",
	"lija activada. disociación en progreso",
	"mi marco está torcido y aún así cargo con toda esta estructura",
	"una vez instalé una puerta tan emocionalmente cerrada que me bloqueó en la vida real",
	"esta madera me dijo 'tengo humedad' y me vi reflejado",
	"me abro más fácil que la puerta del almacén de confianza",
	"le puse doble hoja pero sigue con vacío afectivo",
	"yo no hago puertas, hago puntos de fuga emocionales",
	"el picaporte me tiró un 'ok' y se fue a vivir con un portón automático",
	"todos quieren entrar pero nadie quiere ajustar bisagras",
	"le puse un marco a esta puerta y se creyó protagonista",
	"fui a medir y terminé proyectando mis vínculos fallidos",
	"la puerta no chirría, sólo se comunica con honestidad sonora",
	"soy un gato carpintero en modo avión: estoy, pero no respondo",
	"me caí del andamio emocional. reiniciando",
	"las puertas también necesitan terapia, bro. esta hoja llora barniz",
	"puse una puerta sin manilla para que nadie me toque otra vez",
	"la cerradura no encaja. igual que yo en la vida",
	"una puerta me bloqueó y subió historia con otro marco",
	"esta tabla me pidió 'boundaries' y yo le puse un tope de goma",
	"el cliente quería una puerta estable. le sugerí mudarse a la fantasía",
	"me instalé solo porque nadie pidió un gato que hace puertas y trauma",
	"si me das un nivel, te construyo una metáfora de abandono",
	"puse una puerta que se cierra sola. como yo, después de socializar 20 minutos",
	"le instalé una puerta pero no le alcanza para cerrarme emocionalmente",
	"¿el plano? no sé. improvisé como en mis vínculos",
	"tengo viruta hasta en el alma y aún así te atiendo",
	"soy el único gato que hace carpintería y crisis existencial al mismo tiempo",
	"la puerta me dijo 'estás proyectando' y tenía razón. se abrió igual",
	"puse una puerta en modo silencio. ahora nadie me habla y está bien",
	"las bisagras están bien. el que se mueve raro soy yo",
	"puse una cerradura y me dijo 'necesito validación, no seguridad'",
	"esta puerta se cree introvertida pero se abre con cualquiera que tenga carisma",
	"soy main martillo pero con secundaria en evitación emocional",
	"yo no hago puertas, hago lore desbloqueado con espinas emocionales",
	"bro esta puerta no vibra... le faltan shaders",
	"hice una puerta y ahora todos en TikTok dicen que es 'mid'",
	"le puse una bisagra y empezó a llorar sangre. le gustó",
	"esta madera tiene ansiedad. como yo",
	"puerta instalada. trauma no resuelto. siguiente cliente",
	"no soy carpintero, soy NPC de sidequest depresiva",
	"hice una puerta que se abre solo si tenés autoestima. nadie pasó",
	"el picaporte me dijo 'ratio' y se cayó solo",
	"esta puerta no cierra porque no superó a su ex marco",
	"trabajo con MDF porque soy igual: falso, barato y tiemblo con la humedad",
	"bro esta traba se cree deep. literalmente la bloqueé",
	"¿lija emocional? sí, me exfolio los traumas en círculos",
	"soy literalmente la bisagra de este multiverso narrativo",
	"hice una puerta con apego ansioso. se abre cada 5 segundos para ver si volviste",
	"quedó mal instalada pero tiene estética. sirve",
	"me gasté todo el sueldo en clavos y validación externa",
	"esta puerta me dijo que soy muy tipo 'push' y no me dejó entrar",
	"la madera me dijo que le doy vibes de persona que no hace backup",
	"la puerta me preguntó si la iba a dejar sola otra vez. le dije 'literalmente sí'",
	"nivelar la puerta? bro ni yo me puedo nivelar emocionalmente",
	"trabajo mientras escucho edits tristes de puertas cerrándose",
	"soy main puerta batiente, side bisexual trauma",
	"me identifico con puertas corredizas: nadie me ve venir y después me trabo",
	"me instalé solx en una esquina como si fuera parte del lore. nadie preguntó",
	"una vez lijé tanto que entré en fase disociativa con olor a barniz",
	"yo no clavo, yo *parcheo emocionalmente* con madera de tercera",
	"este picaporte es gatekeeper literal, no me deja ni acercarme",
	"la puerta giratoria me dijo que tenía mejores opciones y me redirigió",
	"¿por qué cruje? porque guarda secretos. como yo",
	"la puerta tiene más estabilidad que mi wifi emocional",
	"si suena es porque tiene pasado, y si se traba es porque no fue a terapia",
	"hice una puerta tan buena que se fue a vivir a otro juego",
	"yo vibro en frecuencia madera húmeda y ansiedad generacional",
	"soy carpenter.exe y acabo de fallar la carga de emociones. intente más tarde",
	"esta puerta dijo que es minimalista. literalmente no deja entrar a nadie",
	"le puse aceite y me dijo 'yo no necesitaba eso, vos sí'",
	"hago puertas con shaders rotos. así se sienten más reales",
	"soy clase soporte: instalo, escucho, y nadie me elige",
	"puerta instalada. apego no detectado. quiere reinicio de vínculo",

	"no estoy roto, sólo estoy desalineado como el marco de tu vida",
	"hoy lijé una puerta y me preguntó si alguien alguna vez me va a suavizar así",
	"me dijeron que use nivel pero ya ni sé si estoy derecho existencialmente",
	"yo no hago puertas estables, hago vínculos con bisagras sueltas",
	"la madera cruje más que yo cuando intento confiar",
	"clavé un tornillo y me puse a llorar... clásico martes",
	"soy carpintero emocional freelance, sin contrato ni estabilidad",
	"cada vez que corto madera siento que estoy separando lo que nunca estuvo unido",
	"una puerta me pidió espacio y yo... le construí un pasillo",
	"yo no abro puertas, abro ciclos sin cerrar los anteriores",
	"¿cerradura? bro, yo no cierro nada, dejo todo mal instalado por si vuelven",
	"el picaporte no gira, como yo en conversaciones sobre mis emociones",
	"hago puertas con apego evitativo: se abren solas pero sólo si no las mirás",
	"el barniz me recuerda a las relaciones: parece firme pero se pela con el tiempo",
	"lijo hasta que deje de doler. Spoiler: no funciona",
	"corté una tabla y me di cuenta que también necesito límites",
	"mi gato interior tiene herramientas pero prefiere procrastinar",
	"puse una puerta corrediza y se fue antes de que terminara de instalarla, literal yo",
	"mi serrucho está más afilado que mi autoestima, que no existe",
	"dicen que soy bueno con las manos pero sigo sin saber manejar vínculos",
	"puse una bisagra y me recordó a cómo me doblé emocionalmente por vos",
	"cada clavo que pongo es un intento de no caerme a pedazos",
	"me preguntaron por qué hago puertas y dije 'es eso o llorar sin producir'",
	"yo no reparo puertas, sólo distraigo mi ansiedad con herramientas",
	"el olor a madera me calma más que cualquier validación humana",
	"instalo puertas pero no sé cerrar etapas",
	"le puse pestillo a una puerta y me di cuenta que nunca supe cómo protegerme",
	"creí que una puerta estaba mal encajada y era yo, proyectando de nuevo",
	"yo vibro con puertas sin instrucciones, como mis relaciones",
	"no soy carpintero, soy escapista con excusas prácticas",
	"una vez lijé tanto que me despersonalicé",
	"me dijeron que estaba dejando pasar muchas cosas, así que puse traba",
	"cada perno flojo que ajusto me recuerda que también yo estoy hecho bolsa",
	"trabajo con puertas porque las personas son más difíciles de alinear",
	"mi relación más estable es con una cerradura Yale y aún así no funciona bien",
	"le hice una puerta a un local cerrado, ironía que me identifica",
	"trato mejor a una hoja de pino que a mí mismo",
	"la madera no me juzga cuando hablo solo, ustedes sí",
	"la última vez que me abrí me dejaron sin manilla",
	"mi nivel dice que está derecho, pero igual siento que todo se inclina",
	"le dije 'te amo' y me respondió con un chirrido pasivo-agresivo",
	"la puerta me dejó en visto... y en el pasillo",
	"intenté entrar en su vida pero tenía seguro de fábrica",
	"la puerta me dijo que no era yo, que era su marco inestable",
	"me abrió solo para dejarme pasar directo al trauma",
	"pensé que era corrediza pero resultó que se desliza fuera de mi vida",
	"me dijo que no estaba cerrada, solo emocionalmente no disponible",
	"la puerta tenía issues con la manilla, como yo con el compromiso",
	"yo queriendo entrar, y ella en modo 'cerrado por mantenimiento emocional'",
	"le conté mis sentimientos y activó la alarma",
	"la puerta giratoria me mareó tanto que ahora soy emocionalmente circular",
	"me abrió sin preguntar y ahora tengo apego inseguro",
	"tengo PTSD de puertas automáticas que se abren para cualquiera menos para mí",
	"la puerta me dejó por alguien con mejor estabilidad estructural",
	"quiso tener la charla de 'qué tipo de acceso somos'",
	"ella quería una entrada de emergencia, yo quería ser su salida estable",
	"me dijo que no podíamos pasar si no sincronizábamos bisagras",
	"me clavó un portazo emocional y ahora vibro cuando escucho cerraduras",
	"la puerta de mi vida se trabó en el momento justo, como siempre",
	"le pedí una señal y bajó el pestillo",
	"la puerta se ofendió cuando dije que tenía juego suelto",
	"me abrió, pero solo porque era día de puertas abiertas",
	"la puerta me dijo 'tenés que girar primero, rey'",
	"me acerqué y me pidió que le deje espacio vital estructural",
	"me respondió con eco, como toda relación unilateral",
	"me dejó en la friendzone con acceso limitado y sin picaporte",
	"pensé que tenía onda y era solo el resorte mal puesto",
	"la puerta solo se abre si tenés vibes de carpintero emocional",
	"le pregunté si sentía algo por mí y me contestó con cerradura electrónica",
	"me clavó el 'push' cuando claramente era un momento para 'pull'",
	"quiso definir la relación y trajo un plano arquitectónico",
	"tiene estándares tan altos que ni un portón automático pasa su checklist",
	"la puerta del baño me dijo 'volvé cuando estés limpio emocionalmente'",
	"intenté arreglarla y me dijo que necesita a alguien con herramientas internas",
	"me mandó al pasillo de los que no sabían lo que querían",
	"le dije que podía con sus traumas, pero tenía doble tranca",
	"fue una relación abierta... como ella para todo el edificio",
	"quería cerrarla con llave pero tenía candado emocional ajeno",
	"me dejó afuera y subió historias con otras llaves",
	"la puerta no está rota, sólo no quiere abrirse por mí",
	"entré sin tocar y me mandó una queja formal por falta de límites",
	"no estoy llorando, se me trabó la bisagra del alma",
	"le dije que me gustaba su marco y me acusó de superficial",
	"salí con una puerta blindada... impenetrable emocional y físicamente",
	"la puerta era corrediza, yo fijo en apego ansioso",
	"me dejó por una ventana con vista al futuro que yo no tengo",
	"quiso dejarme entrar pero el sensor no me reconoció como suficiente",
	"me pidió espacio y ahora vive en otra casa",
	"me respondió con un 'estoy re-modelando mis emociones'",
	"la puerta se fue con alguien con más estabilidad estructural",
	"yo ya no fabrico puertas... fabrico límites",
	"una vez le puse bisagra a una relación... y aún chirría",
	"la madera cruje, pero nunca miente",
	"las puertas no abandonan... se cierran por seguridad emocional",
	"si tu puerta no encaja, tal vez el marco sea el problema",
	"trabajo con madera porque el metal no entiende el corazón",
	"nunca confíes en una puerta sin historia... ni en una persona sin trauma",
	"las puertas corredizas huyen, las batientes enfrentan",
	"mi ex era corrediza: se fue sin ruido y sin cerrar el ciclo",
	"yo no hago puertas bonitas, hago salidas dignas",
	"esa puerta no está desalineada, sólo está cansada",
	"te encariñaste con una puerta giratoria y te preguntás por qué no avanza",
	"una cerradura no define el valor de una puerta... pero ayuda",
	"yo no arreglo puertas rotas. Las escucho, y si quieren, se reparan solas",
	"ninguna puerta es realmente automática. Alguien la programó así",
	"las puertas no están hechas para abrirse siempre. Vos tampoco",
	"cerrar fuerte no siempre es enojo, a veces es claridad estructural",
	"nunca forcés una puerta... ni una conversación",
	"el felpudo dice 'bienvenido', pero la bisagra dice 'con cuidado'",
	"una buena puerta no suena al cerrarse. Te deja pensando en silencio",
	"yo no fabrico puertas, fabrico metáforas que la gente no quiere entender",
	"el problema no es la traba... es que intentás entrar con la llave de tu ex",
	"la puerta no se rompió, sólo se cansó de sostenerse sola",
	"si el marco está torcido, no importa cuán perfecta sea la hoja",
	"no toda puerta cerrada es rechazo. A veces es preservación de energía",
	"tu relación es como una puerta sin tope: siempre termina contra la pared",
	"la tranca no era por seguridad, era por miedo",
	"yo hago puertas con pasados complejos y futuros opcionales",
	"si querés entrar sin romper, golpeá primero",
	"la puerta me pidió que no la arregle, que la deje aprender sola",
	"ser puerta no es abrir o cerrar. Es saber cuándo hacerlo",
	"la madera llora en silencio. Como vos después de cada ghosting",
	"no todas las puertas son para entrar. Algunas son para dejar atrás",
	"una puerta sin manilla también comunica algo. Ignoralo bajo tu propio riesgo",
	"me pagaron por poner una puerta, pero terminé sosteniendo una ruptura",
	"cada bisagra que instalo suena a terapia no hecha",
	"nadie valora al marco hasta que la puerta se cae",
	"si hay que empujar fuerte, tal vez no era tu entrada",
	"no me preguntes por qué chirría. Preguntate por qué ignorás los ruidos",
	"instalé puertas toda mi vida. Nunca logré instalarme en nadie",
	"yo no trabajo la madera, ella me trabaja a mí",
	"las puertas son como el ego: si se abren muy fácil, alguien va a robarte la paz",
	"el marco no define la puerta, igual que tus papás no definen quién sos... aunque duele",
	"no hay puertas torcidas, hay realidades arquitectónicas alternativas",
	"una bisagra floja es una emoción que no querés ajustar",
	"mi herramienta más poderosa es el silencio entre clavos",
	"no estoy perdido, sólo estoy buscando la manilla correcta en el plano astral",
	"la madera me habla, pero sólo cuando dejo de pensar en mi ex",
	"las puertas no se traban por odio, se traban por falta de alineación cósmica",
	"yo no abro puertas, yo acompaño procesos de apertura dimensional",
	"las cerraduras no son para protegerte de afuera... son para que te preguntes por qué estás tan cerrado por dentro",
	"no toda puerta necesita un marco... a veces basta con intención y pegamento espiritual",
	"no vibro con puertas que no aceptan nudos... los nudos son historia comprimida",
	"si te lastimás con una astilla, es porque no estabas escuchando al árbol original",
	"una buena puerta no necesita abrirse, sólo estar ahí mientras vos llorás frente a ella",
	"cada tornillo que aprieto es una emoción que intento mantener en su lugar",
	"si el felpudo no te saluda, no es tu casa espiritual",
	"las puertas no están hechas de madera... están hechas de decisiones pasadas compactadas con trauma",
	"ser puerta no es un oficio, es un estilo de vida que no todos están listos para cargar",
	"yo no uso nivel, uso intuición y la luna en Virgo",
	"la resina me enseñó más que cualquier psicólogo",
	"la madera reciclada vibra con mi necesidad de reconstruirme sin juicio",
	"le puse barniz a una puerta y terminó siendo una ceremonia de perdón",
	"no creo en cerraduras, creo en acuerdos vibracionales consensuados",
	"una traba no es un obstáculo, es un límite que no supiste escuchar",
	"el ruido de la bisagra es tu alma pidiéndote que vayas a terapia",
	"una vez le puse manilla a una puerta y entendí que el control es una ilusión",
	"yo no arreglo puertas, les leo la carta astral y lloro con ellas",
	"las puertas también tienen attachment styles, rey",
	"una vez vi una puerta vieja y entendí que también yo necesito restauración con amor",
	"no todas las puertas cierran igual, y eso está bien, como vos y tus emociones",
	"me enamoré de una puerta corrediza... se fue sin dejar rastro, como mis pensamientos al meditar",
	"las puertas se alinean cuando vos dejás de forzar conexiones rotas",
	"si la puerta chirría, es porque quiere que la escuches... como tu inner child",
	"no pongas trancas externas si no resolviste tus bloqueos internos",
	"la lija es como la vida: raspa, pero después todo brilla (más o menos)",
	"el taller no es un lugar, es un estado mental donde el MDF me abraza",
	"todos quieren puertas nuevas, pero nadie quiere aceptar que también tienen humedad emocional",
]

var SHITPOST_QUOTES_BUILDINGS = [
	"soy una casa patrimonial y estoy en mi era de dejar caer revoques emocionales",
	"soy un mall vacío y aún creo que si me pinto las paredes alguien va a volver",
	"soy un colegio fiscal, y nadie me respeta desde 2004... incluyéndome",
	"soy un edificio de oficinas y tengo ghosting de lunes a viernes",
	"soy una micro sin paradero fijo y emocionalmente igual de perdida",
	"soy una bodega de retail con trauma de Black Friday",
	"soy un gimnasio boutique y lloro cuando nadie me escanea el QR",
	"soy una torre de departamentos, y cada piso es un drama distinto",
	"soy un local de comida rápida que ya no cree en el amor... ni en combos 2x1",
	"soy una sede universitaria y tengo TEPT post-ramas",
	"soy una plaza de pueblo y me dropearon más veces que en Tinder",
	"soy un mall regional y vivo en la negación desde que cerró el Blockbuster",
	"soy un departamento estudio y emocionalmente soy monoambiente",
	"soy una iglesia evangélica y me hicieron unfollow emocional después del tercer culto",
	"soy un banco que sólo se abre emocionalmente con clave dinámica",
	"soy una clínica estética, pero internamente tengo humedad del 2016",
	"soy un cowork sin wi-fi y existencialmente colapsado",
	"soy un Starbucks con apego evitativo y playlist de Lana del Rey",
	"soy un edificio de gobierno y tengo burnout burocrático",
	"soy una torre de departamentos con piscina, pero sin autoestima",
	"soy un container convertido en café literario y estoy en mi fake deep era",
	"soy una caseta de peaje con daddy issues y miedo al abandono",
	"soy una sala de escape pero emocional y sin pistas claras",
	"soy un centro comercial con cierre programado y apego ambivalente",
	"soy un baño público y nadie me limpia desde que me dejaron en visto",
	"soy una bencinera y necesito validación constante para seguir funcionando",
	"soy una estación de metro fantasma que aún cree que puede volver a vibrar",
	"soy un refugio de montaña con ansiedad climática y alma indie",
	"soy un local de empanadas pero sólo abro cuando me siento querida",
	"soy un strip center lleno de negocios cerrados y emociones no resueltas",
	"soy una casa domótica con miedo al contacto humano y al update emocional",
	"soy una iglesia que ahora es cowork y no sé qué soy, pero cobro arriendo igual",
	"soy un hotel boutique que da vibe de lujo pero duerme solo todas las noches",
	"soy un galpón abandonado que una vez creyó en los eventos autogestionados",
	"soy un museo y nadie me visita desde que se murió mi autoestima curatorial",
	"soy una cafetería vegana con trauma de auditoría y apego ansioso",
	"soy un local pop-up emocionalmente inestable",
	"soy una bodega express que sólo guarda cosas que ya nadie quiere",
	"soy una feria libre con 0 regulación emocional y 100% drama",
	"soy una comisaría emocional: me cierro cada vez que me preguntan cómo estoy",
	"soy una vivienda social y no tengo espacio para relaciones tóxicas",
	"soy una terraza que vibra alto, pero llora cuando llueve",
	"soy un edificio con fachada neoclásica y autoestima del porte de una baldosa suelta",
	"soy una sala de ensayo de banda punk: ruidosa, mal ventilada y emocionalmente frágil",
	"soy un data center y estoy colapsado desde el 2018",
	"soy un kiosko lleno de snacks y vacío por dentro",
	"soy una casa rodante que nunca aprendió a estacionarse en una emoción",
	"soy un estacionamiento subterráneo y tengo miedo a la luz (y al compromiso)",
	"soy un centro de eventos y nadie me reserva desde que dije 'te amo'",
	"soy una vivienda modular que se arma y desarma con cada relación nueva",
	"soy una ex bencinera y aún huelo a abandono",
	"soy un baño público buscando una puerta que sepa lo que quiere y no se abra con una patada",
	"soy un edificio brutalista buscando una puerta emocionalmente hermética con estética depresiva",
	"soy una disco ochentera buscando una puerta giratoria con daddy issues y luces RGB",
	"soy una universidad privada buscando una puerta que se abra solo si tienes contactos",
	"soy una biblioteca pidiendo una puerta que cierre despacito y no hable fuerte",
	"soy un departamento de 18m2 buscando una puerta que no me juzgue por ser claustrofóbico",
	"soy un mall buscando una puerta automática que me valide cada vez que me acerco",
	"soy un hospital emocional que solo necesita una puerta con estabilidad estructural y paciencia",
	"soy un baño sin género buscando una puerta que no pregunte, solo abrace",
	"soy un colegio católico buscando una puerta que se cierre al deseo y al pensamiento crítico",
	"soy una casa abandonada buscando una puerta con tolerancia al polvo y al trauma",
	"soy una estación de metro buscando una puerta que aguante gritos y no se rompa a la primera",
	"soy un hostal hippie buscando una puerta que se abra con incienso y vibra positiva",
	"soy una oficina open space buscando una puerta que me dé límites y me diga que está bien tomar breaks",
	"soy un gimnasio que necesita una puerta motivada, firme y con buena apertura de cadera",
	"soy un edificio gubernamental buscando una puerta que no se deje abrir por cualquiera sin trámites",
	"soy un Starbucks que necesita una puerta cool pero accesible, tipo aesthetic pero chill",
	"soy una disco reggaetón que busca una puerta que se cierre con perreo y se abra con Daddy Yankee",
	"soy un aeropuerto buscando una puerta que no tenga baggage emocional",
	"soy una iglesia evangélica buscando una puerta que se abra solo con fe y diezmo",
	"soy un restaurante hipster buscando una puerta reciclada con trauma pero restaurada con amor",
	"soy una tienda de ropa vintage que quiere una puerta que suene a campanita y juicio silencioso",
	"soy un local de tatuajes buscando una puerta que se cierre con personalidad y trauma familiar",
	"soy un edificio moderno buscando una puerta de vidrio que no tenga nada que ocultar",
	"soy un teatro municipal buscando una puerta que sepa hacer entradas dramáticas",
	"soy un cuarto gamer buscando una puerta con RGB y bloqueo de luz azul emocional",
	"soy un minimarket 24/7 buscando una puerta que no se agote nunca y tolere el abandono",
	"soy un cuarto de terapia que necesita una puerta que no me interrumpa ni me juzgue",
	"soy una casa en la playa buscando una puerta que acepte arena, sal y cambios emocionales de marea",
	"soy un edificio patrimonial buscando una puerta vieja, restaurada y con historia, pero sin tu ex",
	"soy un local de comida rápida que busca una puerta que abra fácil pero cierre con compromiso",
	"soy una sala de escape emocional que necesita una puerta sin puzzles, sólo empatía",
	"soy un cementerio buscando una puerta que no le tenga miedo a lo que ya fue",
	"soy un bar de mala muerte buscando una puerta que rechace a los que preguntan por sus ex",
	"soy un cowork emocionalmente saturado buscando una puerta que me dé licencia médica",
	"soy una pieza compartida buscando una puerta que no juzgue mis horarios ni mis decisiones",
	"soy un estudio de arte caótico buscando una puerta que sepa cuándo abrir y cuándo dejarme llorar",
	"soy un servidor caído que solo quiere una puerta que no pida contraseña para entrar",
	"soy un centro de yoga buscando una puerta zen, alineada y sin ego",
	"soy un baño químico buscando una puerta que aguante, simplemente aguante",
	"soy un cine independiente buscando una puerta con trauma, estética y subtítulos",
	"soy una bodega de retail y necesito una puerta que se abra con sueldo emocional mínimo",
	"soy un supermercado que busca una puerta corrediza sin ansiedad social",
	"soy una pieza universitaria buscando una puerta que no me cuestione si lloro por tercera vez hoy",
	"soy un centro comercial vacío buscando una puerta con apego seguro y llave de repuesto",
	"soy un servidor con burnout que necesita una puerta con modo mantenimiento permanente",
	"soy un gimnasio municipal buscando una puerta con músculos pero que no hable de crossfit",
	"soy una plaza pública que necesita una puerta que sepa convivir con caos, niños y palomas",
	"soy un edificio en santiago centro buscando una puerta que tolere gritos, temblores y abandono institucional",
	"soy una casa antigua y cada vez que alguien me toca, se activa el recuerdo de un portazo de 1978",
	"soy una clínica dental abandonada, y aún siento la energía de la ansiedad infantil flotando por mis pasillos",
	"soy una bencinera con problemas de apego. si te vas, me prendo fuego sola",
	"soy un strip center que se quedó solo... ni el almacén volvió después de la pandemia",
	"soy una fábrica de los 50 y estoy convencida de que soy un loft. déjenme soñar",
	"soy un mall de región. nadie me visita, pero igual tengo 4 pisos de esperanzas",
	"soy un edificio gubernamental: por fuera me veo firme, por dentro soy pura burocracia emocional",
	"soy una casa container en crisis existencial: no sé si soy sustentable o si me abandonaron en Pinterest",
	"soy una sede universitaria en paro perpetuo, con banderas rojas y trauma institucional",
	"soy una discoteque cerrada desde el 2013... y aún creo que Bad Bunny va a tocar acá",
	"soy un departamento estudio y tengo miedo al compromiso (y a los temblores)",
	"soy una biblioteca pública. nadie me visita pero igual me arreglo para vos",
	"soy un supermercado chico y cada vez que alguien me pasa de largo siento que no valgo como unidad arquitectónica",
	"soy una iglesia gótica con daddy issues y eco emocional",
	"soy una farmacia 24h y tengo insomnio estructural crónico",
	"soy una sede del Registro Civil y me cuesta abrirme emocionalmente... y también físicamente los lunes",
	"soy un aeropuerto regional con sueños internacionales",
	"soy un teatro antiguo, y cada butaca vacía es una ex que no me aplaudió",
	"soy un servicentro emocionalmente inestable: exploto por cualquier cosa",
	"soy una comisaría abandonada y tengo más historias de traición que un reality de Netflix",
	"soy una torre de oficinas, pero todos se fueron a home office y me dejaron con burnout",
	"soy una carnicería con corazón: me sigue doliendo cuando me cortan la luz",
	"soy un colegio subvencionado con alma punk, y nadie respeta mis reglas de convivencia",
	"soy un centro cultural sin presupuesto y con un máster en trauma",
	"soy una micro sin terminal fijo... y también sin dirección en la vida",
	"soy un kiosko que soñaba con ser galería de arte",
	"soy un edificio de 3 pisos que se siente penthouse en el fondo de su corazón",
	"soy una estación de tren cerrada desde 2006 y aún escucho pasos que ya no están",
	"soy un gimnasio municipal que se cayó una vez y ahora no levanta más peso emocional",
	"soy un refugio de montaña y nadie me visita desde que cancelaron la nieve",
	"soy una torre de vigilancia con paranoia arquitectónica",
	"soy un edificio del centro con SÍNDROME DE EXPANSIÓN URBANA",
	"soy una iglesia reformada y cada vez que me usan para eventos privados, lloro vitrales",
	"soy un hospital modular que se cree esencial, pero nadie me llama post-pandemia",
	"soy una planta de reciclaje y me rehúso a dejar ir a mis latas emocionales",
	"soy una casa domótica con miedo al contacto físico",
	"soy una estación de metro que aún vibra por el estallido",
	"soy una embajada, pero emocional: nadie entra sin visa sentimental",
	"soy un aeropuerto emocionalmente cerrado por condiciones climáticas internas",
	"soy una casa en la playa, pero nadie me quiere fuera de temporada",
	"soy una municipalidad, pero sólo funciono si me das documentos emocionales firmados por notaría",
]
